export const INCREMENT_PAGE_NUMBER = 'INCREMENT_PAGE_NUMBER';
export const SET_PAGE_NUMBER = 'SET_PAGE_NUMBER';
export const RESET_PAGE_NUMBER = 'RESET_PAGE_NUMBER';
export const DECREMENT_PAGE_NUMBER = 'DECREMENT_PAGE_NUMBER';
